"""initial_schema

Revision ID: a0a663b12239
Revises:
Create Date: 2026-09-23 18:29:14.078096
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a0a663b12239'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_rules',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_value', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("target_type IN ('need','concern','mood','fallback')", name='valid_rule_target'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recommendation_rules_lookup', 'recommendation_rules', ['target_type', 'target_value', 'active', 'priority'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('category_label', sa.String(length=100), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=False),
    sa.Column('cover_image', sa.Text(), nullable=True),
    sa.Column('badge', sa.String(length=100), nullable=True),
    sa.Column('key_takeaways', sa.JSON(), nullable=False),
    sa.Column('suggested_action', sa.JSON(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('reading_time_minutes >= 1', name='valid_reading_time'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_category'), 'resources', ['category'], unique=False)
    op.create_index(op.f('ix_resources_published'), 'resources', ['published'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('checkins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mood', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("mood IN ('great','good','okay','stressed','overwhelmed')", name='valid_mood'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkins_user_id'), 'checkins', ['user_id'], unique=False)
    op.create_table('focus_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('session_type', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("session_type = 'focus'", name='valid_focus_type'),
    sa.CheckConstraint("status IN ('in_progress','completed','cancelled')", name='valid_focus_status'),
    sa.CheckConstraint('duration_minutes BETWEEN 1 AND 180', name='valid_focus_duration'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_focus_sessions_user_started', 'focus_sessions', ['user_id', 'started_at'], unique=False)
    op.create_table('checkin_concerns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('checkin_id', sa.Uuid(), nullable=False),
    sa.Column('concern', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint("concern IN ('cant_finish','cant_remember','running_out_of_time','didnt_sleep','worried_exam','racing_thoughts','exhausted','other')", name='valid_concern'),
    sa.CheckConstraint('position BETWEEN 0 AND 2', name='valid_concern_position'),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkin_id', 'concern', name='uq_checkin_concern'),
    sa.UniqueConstraint('checkin_id', 'position', name='uq_checkin_concern_position')
    )
    op.create_index(op.f('ix_checkin_concerns_checkin_id'), 'checkin_concerns', ['checkin_id'], unique=False)
    op.create_table('checkin_needs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('checkin_id', sa.Uuid(), nullable=False),
    sa.Column('need', sa.String(length=50), nullable=False),
    sa.CheckConstraint("need IN ('focus','calm','break','motivated')", name='valid_need'),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkin_id', 'need', name='uq_checkin_need'),
    sa.UniqueConstraint('checkin_id', name='uq_checkin_single_need')
    )
    op.create_index(op.f('ix_checkin_needs_checkin_id'), 'checkin_needs', ['checkin_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('checkin_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkins.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['recommendation_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkin_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_checkin_needs_checkin_id'), table_name='checkin_needs')
    op.drop_table('checkin_needs')
    op.drop_index(op.f('ix_checkin_concerns_checkin_id'), table_name='checkin_concerns')
    op.drop_table('checkin_concerns')
    op.drop_index('ix_focus_sessions_user_started', table_name='focus_sessions')
    op.drop_table('focus_sessions')
    op.drop_index(op.f('ix_checkins_user_id'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_resources_published'), table_name='resources')
    op.drop_index(op.f('ix_resources_category'), table_name='resources')
    op.drop_table('resources')
    op.drop_index('ix_recommendation_rules_lookup', table_name='recommendation_rules')
    op.drop_table('recommendation_rules')
    # ### end Alembic commands ###
